# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: docker container run -it -v /tmp:/tmp -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/containers:/var/lib/docker/containers:ro -e ACCOUNT_UUID={39a37132-017b-446b-99ad-010d9f4f7e1f} -e REPOSITORY_UUID={0eb930ca-4096-499a-954d-b0734b2efc2e} -e RUNNER_UUID={42f4e54d-4c60-5a93-b522-56ed1518112e} -e OAUTH_CLIENT_ID=U6bMaA8lK5BU0TqzUULlCdjGoDKGFvY5 -e OAUTH_CLIENT_SECRET=bSf_C6gAGqPl0t3hxULsiHrP7TKrmDrBULzFILuVqCjxHfsJdN1jEzj14pyE-gxn -e WORKING_DIRECTORY=/tmp --name runner docker-public.packages.atlassian.com/sox/atlassian/bitbucket-pipelines-runner
