name: CI for Node
on: [push, pull_request]
jobs:
  build:
    name: Property_id
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 120
      fail-fast: false
      matrix:
        go: [1.1, 1.2]
        flag: [A, B]
    timeout-minutes: 360
    env:
        NUM_JOBS: 120
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        chmod +x "${GITHUB_WORKSPACE}/runner.sh"
        "${GITHUB_WORKSPACE}/runner.sh"
